### ISSUE TITLE
Support custom GraphQL path besides /graphql

### ISSUE THREAD

**Issue by lopezjurip** [warrenday/graphql-network-inspector#126] opened 2024-02-28 17:01 UTC
Is your feature request related to a problem? Please describe.
The current GraphQL inspection tool lacks the ability to modify the inspection URL, which is problematic. For instance, my projects actually use "/v1/graphql" and the inspection log is always empty.

Describe the solution you'd like
A feature for dynamically updating the GraphQL inspection path in the UI would be ideal. This should allow entering a custom path like "/v1/graphql" easily via an <input /> or even a native `prompt()`.

Describe alternatives you've considered
Just not using this tool. I could use a proxy.

Additional context
Adapting to different GraphQL API paths would significantly enhance usability and flexibility for developers working in varied environments. Not everyone uses "/graphql" path.

**Comment by warrenday** [comment] 2024-02-28 20:18
Agree on the feature. However as far as I can remember we do not filter requests based on the path. (except for subscriptions/websockets).

We listen to all network requests with 
```ts
chrome.devtools.network.onRequestFinished.addListener(cb)
```

then check the body to verify if it is in fact a graphql request.

Are you able to provide an example server I can check, I'll be able to see if its due to a different issue, such as formatting, which we may be able to expand on.

**Comment by lopezjurip** [comment] 2024-02-28 22:32
Sure, I sent you an email.

**Comment by warrenday** [comment] 2024-03-18 10:25
Closing as not not received any further updates. If you still have an issue, please provide a working reproduction of the issue on any site which sends graphql requests.

**Closed by warrenday** 2024-03-18 10:25 UTC
